var path = require('path')                      // For managing paths, ofcourse.
var fs = require('fs')                          // Nodes file system
var request = require('request')                // npm install request!

// Variables
var config = JSON.parse(fs.readFileSync(path.join(__dirname + '/config.json'), 'utf8'));
var filesArray = [];       // Gets populated by init(); An array of all the files and their metadata that need checking on.
var data = {};          // Gets populated by init(); File the client uses to store small bits of data locally.

// Grabs split up metadata such as file name, ext, size, location and returns as dict
function getFileMetadata(filepath) {
    return {
        filename: path.basename(filepath),
        filepath: filepath,
        size: fs.statSync(filepath).size
    };
};

// Go round all the files and collect their file names, size, and other things we can add in
// into a single big array of files that need scanning. Then we can just iterate over that.
function Init() {
    console.log('Client Initializing...');

    // Go through all the config files, resolve them (or not) and add to the filesArray array.
    for (var f = 0; f < config['PathsToScan'].length; f++) {                                            // For every config entry
        if (fs.existsSync(config.PathsToScan[f].Location)) {                                            // If the file or dir exists
            if (fs.lstatSync(config.PathsToScan[f].Location).isFile()) {                                // If it's a file we're looking at
                filesArray.push(getFileMetadata(config.PathsToScan[f].Location));                       // Populate and push
            } else if (fs.lstatSync(config.PathsToScan[f].Location).isDirectory()) {                    // Elif its a dir
                fs.readdirSync(config.PathsToScan[f].Location).forEach(function(filename) {             // for every item in dir
                    if (path.extname(filename) == ".log") {                                             // If it's a .log and nothing but a .log file
                        filesArray.push(getFileMetadata(config.PathsToScan[f].Location + filename));    // Populate and push
                    };
                });
            } else {
                console.warn(`[Warning] I'm unable to detect what "${config.PathsToScan[f].Location}" is. It may be a socket or symlink.`);
            };
        } else {
            console.warn(`[Warning] The file "${config.PathsToScan[f].Location}" does not exist!`);
        };
    };

    // Check if we have a .data.json file to store little bits of client info, such as our unique key
    if (fs.existsSync(path.join(__dirname + '/.data.json'))) {                                          // If the .data.json file exists
        data = JSON.parse(fs.readFileSync(path.join(__dirname + '/.data.json'), 'utf8'));               // Read/Load it into the data varaible as json
    };

    // Launch the webUI as a child if configured
    if (config.WebUI.Enabled) {
        require(__dirname + '/WebUI/launchWebUI.js').WebUI.listen(config.WebUI.Port, config.WebUI.IP);
    };
    console.log('Client Initialized.');
    Authenticate(); // Login to the server
};

// Keeps the data file up to date when changing the data variable
function UpdateData() {
    fs.writeFileSync(path.join(__dirname + '/.data.json'), JSON.stringify(data));
};

// Authenticates with server
function Authenticate() {
    console.log('Authenticating...');

    ////////////////////////////////////////// Developer Note //////////////////////////////////////////////////////
    // LogSee_Key   = The authentication key generated by the admin via server dashboard
    // UniqueKey    = The server-generated key given to the client after successful authentication with LogSee_Key
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Check that the client WebUI config isn't using the default values
    if (config.WebUI.RequireAuth && (config.WebUI.AuthUser == "admin" || config.WebUI.AuthPass == "admin")) {
        console.warn('[Critical] - The WebUI credentials are still set as default. Please change them before running the client.');
        process.exit();
    };

    // Ask if our AuthKey matches that of the servers
    if (config.Client.LogSee_Key && !data.UniqueKey) {
        console.log('Registering client for first time authentication...');
        var options = {
            url: 'http://127.0.0.1:1339/api/authenticate',
            json: {'AuthKey': config.Client.LogSee_Key}
        };
        request.post(options, function(err, response, body) {
            // If success
            if (response.statusCode == 200) {
                console.log(response.statusCode, body.Message);
                data.UniqueKey = body.UniqueKey;
                UpdateData();
                Authenticate();
            } else { // If unsuccess (due to errors or failed key)
                console.log(response.statusCode, body.Message)
            }
        });
    } else if (data.UniqueKey && config.Client.LogSee_Key) { // We have an auth + unique key
        console.log('Client already registered... Checking status...');
        var options = {
            url: 'http://127.0.0.1:1339/api/authenticate',
            json: {'AuthKey': config.Client.LogSee_Key, 'UniqueKey': data.UniqueKey}
        };
        request.post(options, function(err, response, body) {
            console.log(response.statusCode, body.Message);
            if (response.statusCode == 200) {
                console.log('Client successfully authenticated.')
                Pinger();
                // Send all these files to the API to ensure they're in the DB
                request.post({url: 'http://127.0.0.1:1339/api/addfiles', json: {"Data": filesArray, "UniqueKey": data.UniqueKey}}, function(err, response, body) {
                    if (response.statusCode == 200) {
                        ScanFiles();
                    };
                });
                
            } else if (response.statusCode == 404) { // No unqiue key record was found, generate a new one
                data.UniqueKey = null;
                UpdateData();
                console.log('Server did not recognize us. A new UniqueKey has been generated and attemping re-authentication.')
                Authenticate();
            } else if (response.statusCode == 403) { // Denied. Stop asking.
                process.exit();
            } else if (response.statusCode == 401) { // Awaiting approval
                console.log('Waiting 30s to try again...');
                setTimeout(function() {
                    Authenticate();
                }, 30000) // Check again every 30 seconds
            };
        });
    } else {
        console.log('Unable to authenticate with the server as no LogSee_Key has been given.\nPlease create a key via the server dashboard and insert it into the config file.')
        process.exit();
    };
};

// Iterates over the configured files and checks for file changes, reports them.
function ScanFiles() {
    setInterval(function() {
        // Iterate over each file
        for (var f = 0; f < filesArray.length; f++) {
            // If the byte size != the previously logged byte size for that item, read it.
            if (fs.statSync(filesArray[f].filepath).size != filesArray[f].size) {
                filesArray[f].size = fs.statSync(filesArray[f].filepath).size; // Update its file size
                console.log(`New file size detected on file "${filesArray[f].filepath}"`);
                // Todo: IF Metadata.lastLineSent, send from that line
            };
        };
    }, config.Client.ScanFrequency) // Wait the ScanFrequency value, more of a safety than anything
    console.log(`Client is running.`);
};

// Lets the server know every config.Client.PingInterval seconds if it's still alive
function Pinger() {
    setInterval(function() {
        request.post({url: 'http://127.0.0.1:1339/api/pingpong', json: {'UniqueKey': data.UniqueKey} });
    }, config.Client.PingInterval * 1000);
};

Init(); // Run
